projects:
  - name: karpfen.fish
    description: Personal website
    repo:
      url: git@gitlab.com:argo-apps/karpfen.fish.git
      #revision: HEAD
      #type: git
      #secret: custom-key # Store in vault /gitops/ssh/custom-key with key 'private_key'
  - name: karpfen.dev
    description: Homelab apps and tools
    repo:
      url: git@gitlab.com:argo-apps/karpfen.dev.git
  - name: vindi.app
    description: Vindictus Fansite
    repo:
      url: git@gitlab.com:argo-apps/vindi.app.git

credentials:
  - url: git@gitlab.com
    secret: argo-deploy-key
    type: git