projects:
  - name: karpfen.fish
    description: Personal website
    git:
      repo: https://gitlab.com/argo-apps/karpfen.fish
  - name: karpfen.dev
    description: Homelab apps and tools
    git:
      repo: https://gitlab.com/argo-apps/karpfen.dev
  - name: vindi.app
    description: Vindictus Fansite
    git:
      repo: https://gitlab.com/argo-apps/vindi.app
