cloudflared:
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      # It is safe to put a wildcard here
      # Please see https://homelab.karpfen.dev/reference/faq.html#is-it-safe-to-use-wildcard-in-cloudflare-tunnel-ingress-config
      - service: https://ingress-nginx-controller.ingress-nginx
        originRequest:
          noTLSVerify: true

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
