cloudflared:
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - hostname: '*.games.karpfen.dev'
        service: traefik.kube-system
      - service: https://ingress-nginx-controller.ingress-nginx
        originRequest:
          noTLSVerify: true

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
