---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backup-secret
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  dataFrom:
    - extract:
        key: '/longhorn/backup'
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-daily
  namespace: longhorn-system
spec:
  cron: "0 0 * * *"
  task: "snapshot"
  groups:
    - default
  retain: 3
  concurrency: 2
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-weekly
  namespace: longhorn-system
spec:
  cron: "0 0 1 * *"
  task: "snapshot"
  groups:
    - default
  retain: 3
  concurrency: 2
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-monthly
  namespace: longhorn-system
spec:
  cron: "0 0 1 1 *"
  task: "snapshot"
  groups:
    - default
  retain: 3
  concurrency: 2