---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        tls:
          enabled: true
      sf-game:
        expose: true
        protocol: UDP
        port: 7777
      sf-beacon:
        expose: true
        protocol: UDP
        port: 15000
      sf-query:
        expose: true
        protocol: UDP
        port: 15777