seafile:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Seafile
        hajimari.io/icon: google-drive
      hosts:
        - host: &host seafile.karpfen.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: seafile-tls-certificate
          hosts:
            - *host
  persistence:
    shared:
      enabled: true
      type: pvc
      accessMode: ReadWriteMany
      size: 20Gi
      mountPath: /shared/
  mariadb:
    enabled: true
    primary:
      persistence:
        enabled: true
