seafile:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Seafile
        hajimari.io/icon: google-drive
      hosts:
        - host: &host seafile.karpfen.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: seafile-tls-certificate
          hosts:
            - *host
  mariadb:
    enabled: true
  persistence:
    seafile-data:
      enabled: true
      type: pvc
      accessMode: ReadWriteMany
      size: 20Gi
      mountPath: /shared/seafile/seafile-data
    data-mariadb:
      enabled: true
      type: pvc
      accessMode: ReadWriteMany
      size: 1Gi
      mountPath: /var/lib/mysql/

