seafile:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Seafile
        hajimari.io/icon: google-drive
        nginx.ingress.kubernetes.io/proxy-body-size: 0
      hosts:
        - host: &host seafile.karpfen.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: seafile-tls-certificate
          hosts:
            - *host
  env.SEAFILE_SERVER_HOSTNAME: seafile.karpfen.dev
  persistence:
    shared:
      enabled: true
      type: pvc
      accessMode: ReadWriteMany
      size: 20Gi
      mountPath: /shared/
    seafdav:
      enabled: true
      type: configMap
      mountPath: /opt/seafile/conf/seafdav.conf
      data:
        {{ (.Files.Glob "files/config/*").AsConfig | indent 2 }}
  mariadb:
    enabled: true
    primary:
      persistence:
        enabled: true
