seafile:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Seafile
        hajimari.io/icon: google-drive
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.org/server-snippets: |
          location /seafdav {
            proxy_pass         http://127.0.0.1:8080/seafdav;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_read_timeout  1200s;
            client_max_body_size 0;
          ﻿
            access_log      /var/log/nginx/seafdav.access.log seafileformat;
            error_log       /var/log/nginx/seafdav.error.log;
          }
      hosts:
        - host: &host seafile.karpfen.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: seafile-tls-certificate
          hosts:
            - *host
  env.SEAFILE_SERVER_HOSTNAME: seafile.karpfen.dev
  mariadb:
    enabled: true
    primary:
      persistence:
        enabled: true
  persistence:
    shared:
      enabled: true
      type: pvc
      accessMode: ReadWriteMany
      size: 20Gi
      mountPath: /shared/
    seafdav-config:
      enabled: true
      type: configMap
      name: seafdav-config
      mountPath: /opt/seafile/conf/seafdav.conf
      subPath: seafdav.conf
