cloudflared:
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab-udp
    ingress:
      - service: udp://traefik-udp.kube-system

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
