passbolt:
  service:
    name: http
    port: 80
    targetPort: 80
  passboltEnv:
    plain:
      PASSBOLT_SSL_FORCE: false
      APP_FULL_BASE_URL: https://passbolt.karpfen.dev
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Passbolt
      hajimari.io/icon: logos:passbolt-icon
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
      external-dns.alpha.kubernetes.io/target: homelab-tunnel.karpfen.dev
    hosts:
      - host: &host passbolt.karpfen.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: passbolt-tls
        hosts:
          - *host