---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        password: {{` "{{ .password }}" `}}
  dataFrom:
    - extract:
        key: /passbolt/redis

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        mariadb-root-password: {{` "{{ .password }}" `}}
        mariadb-username: {{` "{{ .password }}" `}}
        mariadb-password: {{` "{{ .password }}" `}}
        mariadb-replication-password: {{` "{{ .password }}" `}}
  dataFrom:
    - extract:
        key: /passbolt/mariadb
